# Generated by Django 4.1.6 on 2023-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('nazer', 'nazer'), ('operator', 'operator'), ('admin', 'admin')], max_length=15, null=True),
        ),
    ]
